//! Bot Orchestrator — auto-proposes a draft SOW to `compliance_service`
//! when a talent match score reaches the high-confidence threshold (≥ 0.85).
//!
//! The proposal is fire-and-forget: it runs in a spawned Tokio task so it
//! never blocks the match response.  Failures are logged but not surfaced to
//! the caller.

use std::time::Duration;

use base64::Engine;
use reqwest::Client;
use tracing::{error, info, warn};
use uuid::Uuid;

/// Minimum Jaccard match score that triggers an automatic SOW proposal.
pub const SOW_THRESHOLD: f32 = 0.85;

/// Thin HTTP client that posts draft SOW contracts to `compliance_service`.
#[derive(Clone)]
pub struct SowOrchestrator {
    client: Client,
    compliance_url: String,
}

impl SowOrchestrator {
    pub fn new(compliance_url: String) -> Self {
        let client = Client::builder()
            .timeout(Duration::from_secs(10))
            .build()
            .expect("reqwest client init");
        Self {
            client,
            compliance_url,
        }
    }

    /// Fires an async SOW draft creation request.
    /// Returns immediately — call from `tokio::spawn`.
    pub async fn propose_sow(
        &self,
        agent_id: Uuid,
        developer_id: Uuid,
        talent_id: Uuid,
        match_score: f32,
    ) {
        let doc = format!(
            "STATEMENT OF WORK (AUTO-PROPOSED)\n\
             Agent:       {agent_id}\n\
             Developer:   {developer_id}\n\
             Talent:      {talent_id}\n\
             Match Score: {match_score:.2}\n\
             Status:      PENDING_SIGNATURE\n\
             \n\
             This SOW was auto-generated by the AiStaff Bot Orchestrator \
             because the talent match score exceeded the {:.0}% threshold.\n\
             Both parties must review and sign before any deployment begins.",
            SOW_THRESHOLD * 100.0,
        );

        let doc_b64 = base64::engine::general_purpose::STANDARD.encode(doc.as_bytes());

        let body = serde_json::json!({
            "contract_type": "SOW",
            "party_a":       developer_id,
            "party_b":       talent_id,
            "deployment_id": null,
            "document_b64":  doc_b64,
        });

        match self
            .client
            .post(format!("{}/contracts", self.compliance_url))
            .json(&body)
            .send()
            .await
        {
            Ok(resp) if resp.status().is_success() => {
                info!(
                    %agent_id, %talent_id, match_score,
                    "Bot Orchestrator: auto-proposed SOW draft"
                );
            }
            Ok(resp) => {
                warn!(
                    status = %resp.status(),
                    %agent_id, %talent_id,
                    "compliance_service rejected SOW proposal"
                );
            }
            Err(e) => {
                error!(%agent_id, %talent_id, "Failed to reach compliance_service: {e}");
            }
        }
    }
}
